### ISSUE TITLE
Incompatible arch

### ISSUE THREAD

**Issue by nw0428** [antonvh/mpy-robot-tools#6]
I get the following when I try to import anything:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: incompatible .mpy arch

My `sys.implementation.mpy` is 517

**Comment by antonvh** [comment]
Could you be more specific? What hardware are you using? How did you install the lib? What are you trying to achieve?

**Comment by antonvh** [comment]
Closing this, no response anymore.
